const router=require('express').Router();
const {saveDocument,createDraft,createYourselfdraft,handleSaveAsTemplate,createSignTemplate,duplicateTemplate,saveTemplate,deleteDocument,deleteDraft,getDrafts,declineDocs,getCompletedDocs,getExpiredDocs,getDeclinedDocs,getInProgressDocs,getNeedSignDocs,deleteTemplate,getAllTemplates,assignEmailToRole,embedElementsInPDF,recentSentRequest,recentSignatureRequest,getSpecificDoc,getUserFiles,signDocument,sendSignRequest,getUserDocuments,editDocument}=require('../controller/user/document')
const {auth}=require('../middleware/auth')
const uploadMulter=require('../middleware/file')
router.post('/saveDocument',auth,uploadMulter.single("document"),saveDocument)
router.get('/getUserDocuments',auth,getUserDocuments)
router.post('/saveTemplate',auth,uploadMulter.single("document"),saveTemplate)
router.get('/recentSignatureRequest',auth,recentSignatureRequest)
router.get('/getAllTemplates',auth,getAllTemplates)
router.delete('/deleteTemplate/:id',deleteTemplate)
router.post('/createSignTemplate',createSignTemplate)
router.get('/recentSentRequest',auth,recentSentRequest)
router.patch('/editDocument/:docId',auth,uploadMulter.single("document"),editDocument)
router.delete('/deleteDocument/:id',auth,deleteDocument)
router.post('/sendSignRequest',auth,sendSignRequest)
router.post('/duplicateTemplate',auth,duplicateTemplate)
router.get('/getSpecificDoc/:docId',auth,getSpecificDoc)
router.patch('/signDocument',auth,signDocument)
router.post('/createDraft',auth,uploadMulter.single('document'),createDraft)
router.post('/createYourselfdraft',auth,uploadMulter.single('document'),createYourselfdraft)
router.patch('/declineDocs',auth,declineDocs)
router.get('/getUserFiles',auth,getUserFiles)
router.post('/embedElementsInPDF',auth,uploadMulter.single("document"),embedElementsInPDF)
router.patch('/assignEmailToRole',auth,assignEmailToRole)
router.get('/getNeedSignDocs',auth,getNeedSignDocs)
router.get('/getInProgressDocs',auth,getInProgressDocs)
router.get('/getCompletedDocs',auth,getCompletedDocs)
router.get('/getDeclinedDocs',auth,getDeclinedDocs)
router.get('/getExpiredDocs',auth,getExpiredDocs)
router.get('/getDrafts',auth,getDrafts)
router.patch('/handleSaveAsTemplate/:id',handleSaveAsTemplate)
router.delete('/deleteDraft/:docId',deleteDraft)
module.exports=router;